language: go


go:
  - 1.7.x
  - 1.8.x

before_script:
  - go get -t -v github.com/vlorc/gioc/...

script:
  - go test -v github.com/vlorc/gioc/

notifications:
  email:
    recipients: sapaid@qq.com
    on_success: change
    on_failure: always